name: Build

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build onefile for win
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install deps
        run: |
          pip install wheel pyinstaller -U

      - name: Build
        run: bash create_win_onefile.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: onefile
          path: dist/*
          if-no-files-found: error
